name: main test the deployed
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 压缩文件夹 
        run: |
          zip -q -r dist.zip ./public
          ls
      - name: 同步文件到服务器
        uses: garygrossgarten/github-action-scp@release
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          password: ${{secrets.PASSWORD}}
          local: "./dist.zip"
          remote: ${{secrets.SERVER_PATH}}
      - name: 解压文件
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /bzp
            unzip dist.zip -d www
            rm dist.zip
            